FROM python:3.10-slim
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /visitor_backend
COPY requirements.txt /visitor_backend/requirements.txt
COPY packages/ /visitor_backend/packages
COPY manage.py
RUN pip install --no-index --find-links=/visitor_backend/packages -r /visitor_backend/packages
COPY ..
EXPOSE 8010
CMD ["python3", "manage.py", "runserver", "0:8010"]