# Generated by Django 5.2.13 on 2026-04-24 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(default='', max_length=100)),
                ('host_email', models.EmailField(default='', max_length=15)),
                ('department', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'host',
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=15)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('security', 'Security'), ('host', 'Host')], default='security', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(default='', max_length=30)),
                ('visitor_email', models.EmailField(default='', max_length=15)),
                ('phoneNumber', models.CharField(default='', max_length=10)),
                ('id_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('pin', 'PIN')], default='national_id', max_length=20)),
                ('id_number', models.CharField(default='', max_length=20, unique=True)),
                ('visit_type', models.CharField(choices=[('internal', 'Internal'), ('external_appointment', 'External Appointment'), ('external_walkin', 'External Walkin')], default='external_walkin', max_length=25)),
                ('organization', models.CharField(default='', max_length=100)),
                ('status', models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('expected_duration_mins', models.PositiveIntegerField(default=30, help_text='Duration in minutes')),
                ('purpose', models.TextField(default='', max_length=500)),
                ('check_in_at', models.DateTimeField(blank=True, null=True)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.host')),
            ],
            options={
                'db_table': 'visit',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='')),
                ('detail', models.TextField(default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='visitor.profiles')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.visit')),
            ],
            options={
                'db_table': 'audit',
            },
        ),
    ]
